# need to download and setup https://docs.aws.amazon.com/lambda/latest/dg/go-image.html in the section "Using a non-AWS base image" for the aws-lambda-rie stuff
services:
  lambda-func:
    image: go-sqs-lambda:local
    ports: 
        - 9000:8080
    volumes:
      - ~/.aws-lambda-rie:/aws-lambda
      - ~/.aws:/root/.aws
    environment:
      - S3_BUCKET=go-sqs-project-bucket
      - AWS_REGION=us-east-1
      - ENCRYPTION_KEY_PATH=/go-sqs-project/ENCRYPTION_KEY
    entrypoint: /aws-lambda/aws-lambda-rie ./main