name: lambda setup

on: 
  push:
    branches:
      - 'main'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
  DOCKER_IMAGE_URI: public.ecr.aws/v6i6h5l0/go-sqs-lambda:latest

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::785210909375:role/github-actions-role-go-sqs
          aws-region: us-east-1
      - 
        name: auth to docker
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 785210909375.dkr.ecr.us-east-1.amazonaws.com
      # - 
        # name: Build Image
        # working-directory: './lambda_function'
        # run: docker build -t ${{ env.DOCKER_IMAGE_URI }} .
      # -
      #   name: Push Image
      #   run: docker push ${{ env.DOCKER_IMAGE_URI }}
      - 
        name: list docker images
        run: docker image ls