name: lambda setup

on: 
  push:
    branches:
      - 'main'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
  DOCKER_IMAGE_TAG: ${{ secrets.DOCKER_USERNAME }}/go-sqs-lambda:${{ github.sha }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Login to docker
        run: docker login -u ${{ env.DOCKER_USERNAME }} -p ${{ env.DOCKER_PAT }}
      - 
        name: Build Image
        working-directory: './lambda_function'
        run: docker build -t ${{ env.DOCKER_IMAGE_TAG }} .
      -
        name: see images
        run: docker push ${{ env.DOCKER_IMAGE_TAG }}